### ISSUE TITLE
Ability to render README.Rmd locally

### ISSUE THREAD

**Issue by bahadzie** [epiverse-trace/etdev#12]
It would be nice to see the rendered version of README.Rmd locally before committing to a repo and waiting for Github actions to render it. 

Benefits
- Update, render and preview README.md locally until your satisfied before committing
- Faster iterations because its rendered locally instead of _centuries_ later by a Github action online
- No need to fetch/pull the rendered README.md back down (in theory) = Less friction = Improved quality of life

**Comment by chartgerink** [comment]
You can render the README.rmd locally as well, so closing this as it is already possible and the thread has been open without activity for >6 months.
