### ISSUE TITLE
minor modifications for easier understanding

### ISSUE THREAD

**Issue by bahadzie** [epiverse-trace/etdev#3]
I propose the following changes to .lintr files in epiverse packages

```r
linters: linters_with_tags(
    tags = NULL, # include all linters
    object_name_linter = NULL,
    undesirable_function_linter = NULL,
    implicit_integer_linter = NULL,
    extraction_operator_linter = NULL,
    todo_comment_linter = NULL,
    function_argument_linter = NULL,
    # Use minimum R declared in DESCRIPTION or fall back to current R version
    backport_linter(if (length(x <- etdev::extract_min_r_version())) x else getRversion())
    # install.packages("remotes")
    # remotes::install_github("epiverse-trace/etdev")
  )
exclusions: list("R/RcppExports.R")
```
I made the assumption that `etdev` was on CRAN and initially commented it out to continue working.

It was only after googling that I discovered it was `epiverse-trace` specific. The extra comments after `backport_linter` are from the README.md and will hopefully help me or others in future.

Also in the R\ folder the file is called [extra_min_r_version.R](https://github.com/epiverse-trace/etdev/blob/main/R/extra_min_r_version.R) but the function is called `extract_min_r_version` for consistency sake it would be nice to name the file after the function.

**Comment by Bisaloo** [comment]
Thanks for the report!

Fixed by https://github.com/epiverse-trace/packagetemplate/commit/fc161d6ef48784bb6cf8b87e059684cd4a95c388 and 0ced8f6bbd0b0ac4dd78c61b4e275761c939eef4.
